CREATE TABLE playground
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(255),
    location    VARCHAR(255),
    rating      INTEGER,
    feedback    VARCHAR(255),
    date        DATE,
    PRIMARY KEY (id)
);

CREATE TABLE addresses
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    city     VARCHAR(20),
    state    VARCHAR(20),
    zipcode  VARCHAR(10),
    playground_id BIGINT,  -- Foreign key to playground table
    CONSTRAINT fk_playground FOREIGN KEY (playground_id) REFERENCES playground (id)
);
